# CAS CONFIG
#
# This file is used to generate the data for the sites you want to manage.

# Config: global configuration across all sites
config:

  # TODO - clarify what is the initial password
  initial_admins:
    - admin@example.com

  # Superadmins can create other admins and users. Define which emails or logins
  # you want set as superadmin.
  superadmins:
    - admin@example.com
    - superadmin-login

  # DEPRECATED
  uploads:
    cache_directory_prefix: 'cache'
    store_directory_prefix: 'uploads'

# Sites: define the ones you want to manage. If you have multiple, you will be
# able to switch between them inside Cas dashboard.
#
# Each site has Sections, and each Section has their own Categories.
sites:
  mysite:
    name: mysite.net

    # Depending on this, Cas will automatically switch the site it is managing.
    domains:
      - mysite.net

    # These are entire sections, like 'articles', 'pages', 'ads' etc
    sections:
      news:
        name: news
        type: content
        list_fields:
          - title
          - category
        fields:
          - category
          - tags
          - title
          - summary
          - text
          - images
          - biography:
              label: "Related biography"
          - files
          - tags
          - date
        has_many:
          - biography
      biography:
        name: Biography
        type: content
        fields:
          - title
          - text
          - image
      agenda:
        name: Agenda
        type: content
        accessible_roles:
          - admin
        list_fields:
          - title
          - date_time
        list_order_by:
          - order_field
        fields:
          - title
          - location
          - date:
              language: pt-br
              format:
                - day
                - month
                - year
          - text
      survey:
        name: Survey
        type: survey
